# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2169c7cbce31e68bd57d83bd6ffd32e47e2103d4977c9cf461658f452ac3379ea7189721d2712990900c954c9d2b8b75d03810fff534dba6a1f92c343d325292

test:
  secret_key_base: 6c99e1e186ba37a89b4f5f7f3a6a05806731c5a53ada97f12ce92225b31c885868cde1d4a64394e78f8b5414e1a137d7d7322291341d8d5322cae80fff03dfea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
